#define IDH_IDH_TOPIC_NOT_FOUND         999
#define IDH_IDH_ABOUT                   208
#define IDH_BBBC_ABOUT                  208
#define IDH_BBBC_BROWSE                 222
#define IDH_BBBC_BROWSERSTYLES          224
#define IDH_BBBC_CREATENEWFOLDER        223
#define IDH_BBBC_DECRYPT                203
#define IDH_BBBC_ENCRYPT                202
#define IDH_BBBC_EXIT                   207
#define IDH_BBBC_HELP                   209
#define IDH_BBBC_MAIN                   201
#define IDH_BBBC_OPTIONS                206
#define IDH_BBBC_PATHINPUT              225
#define IDH_BBBC_REFRESH                221
#define IDH_BBBC_UPONELEVEL             220
#define IDH_BBBC_WIPE                   204
#define IDH_BBBC_WORKWITH               205
#define IDH_DIALOG_CHANGEPATH           502
#define IDH_DIALOG_CLEAREMPTYDISKSPACE  504
#define IDH_DIALOG_DESTINATION          506
#define IDH_DIALOG_JOBREPORT            507
#define IDH_DIALOG_KEYINPUT             505
#define IDH_DIALOG_MAKEKEYDISK          501
#define IDH_DIALOG_PROGRESS             508
#define IDH_DIALOG_SDFC                 503
#define IDH_GENERAL_BROWSER             108
#define IDH_GENERAL_COPYRIGHT           103
#define IDH_GENERAL_CREDITS             106
#define IDH_GENERAL_DRAGDROP            107
#define IDH_GENERAL_INTRO               100
#define IDH_GENERAL_JOBFILES            110
#define IDH_GENERAL_KEYCACHE            111
#define IDH_GENERAL_LANGUAGE            112
#define IDH_GENERAL_POPUPMENU           109
#define IDH_GENERAL_SECURITY            105
#define IDH_GENERAL_TECHREF             104
#define IDH_GENERAL_WHERETOGET          101
#define IDH_MENU_CHOOSEFONT             405
#define IDH_MENU_DESLACK                403
#define IDH_MENU_EXCLUDEFILES           404
#define IDH_MENU_EXPIREKEYCACHE         409
#define IDH_MENU_FAVORITES              400
#define IDH_MENU_REENCRYPT              402
#define IDH_MENU_SCANNER                406
#define IDH_MENU_SHOWBROWSERTOOLS       408
#define IDH_MENU_SHOWBUTTONBAR          407
#define IDH_MENU_VIEW                   401
#define IDH_OPTIONS_CONFIGURATION       303
#define IDH_OPTIONS_FILEHANDLING        304
#define IDH_OPTIONS_MISC                305
#define IDH_OPTIONS_MAIN                301
#define IDH_OPTIONS_SECURITY            302
